# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StageTracker.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 427)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("echidna.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tracker_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.tracker_groupBox.setGeometry(QtCore.QRect(0, 10, 401, 401))
        self.tracker_groupBox.setObjectName("tracker_groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tracker_groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 19, 381, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.tracker_holder = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.tracker_holder.setContentsMargins(0, 0, 0, 0)
        self.tracker_holder.setObjectName("tracker_holder")
        self.move_Button = QtWidgets.QPushButton(self.centralwidget)
        self.move_Button.setGeometry(QtCore.QRect(410, 30, 146, 23))
        self.move_Button.setObjectName("move_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stage Mover"))
        self.tracker_groupBox.setTitle(_translate("MainWindow", "Stage Tracker"))
        self.move_Button.setText(_translate("MainWindow", "Move Random"))
